/*
Copyright © 2026 HNCLR by Poyraz Boreas Hancilar
Licensed under the Apache License, Version 2.0
*/
package cmd

import (
	"encoding/pem"
	"fmt"
	"math"
	"os"

	"github.com/spf13/cobra"
)

type ScoreResult struct {
	FilePath     string  `json:"file_path"`
	Entropy      float64 `json:"entropy"`
	TrustScore   int     `json:"trust_score"`
	Assessment   string  `json:"assessment"`
	ErrorMessage string  `json:"error_message,omitempty"`
}

var scoreCmd = &cobra.Command{
	Use:   "score [file/dir]",
	Short: "Analyze cryptographic entropy and trust score",
	Long:  `Score calculates the Shannon Entropy of a key to detect weak PRNG generation or structural anomalies.`,
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) < 1 {
			fmt.Println(colorize("Error: Please specify file or directory.", colorRed))
			return
		}
		HandlePath(args[0], PerformScore)
	},
}

func PerformScore(filePath string) {
	result := ScoreResult{
		FilePath: filePath,
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		result.ErrorMessage = fmt.Sprintf("Error reading file: %v", err)
		printScoreResult(result)
		return
	}

	block, _ := pem.Decode(data)
	if block == nil {
		result.ErrorMessage = "Not a valid PEM block for entropy analysis."
		printScoreResult(result)
		return
	}

	// Calculate Shannon Entropy on the raw DER bytes
	entropy := calculateEntropy(block.Bytes)
	result.Entropy = entropy

	// Heuristic Trust Score (0-100)
	// Perfect entropy is 8.0. Below 7.5 is highly suspicious for keys.
	trustScore := int((entropy / 8.0) * 100)
	
	// Add penalization for specific low ranges
	if entropy < 7.0 {
		trustScore -= 30
	} else if entropy < 7.5 {
		trustScore -= 15
	}

	if trustScore < 0 { trustScore = 0 }
	result.TrustScore = trustScore

	// Assessment
	if trustScore > 90 {
		result.Assessment = "Excellent: High randomness detected."
	} else if trustScore > 75 {
		result.Assessment = "Good: Standard cryptographic randomness."
	} else if trustScore > 50 {
		result.Assessment = "Suspicious: Low entropy detected. May be generated by a weak PRNG."
	} else {
		result.Assessment = "CRITICAL: Highly predictable data. Do NOT use this key."
	}

	printScoreResult(result)
}

func calculateEntropy(data []byte) float64 {
	if len(data) == 0 {
		return 0
	}

	frequencies := make(map[byte]float64)
	for _, b := range data {
		frequencies[b]++
	}

	var entropy float64
	for _, count := range frequencies {
		p := count / float64(len(data))
		entropy -= p * math.Log2(p)
	}

	return entropy
}

func printScoreResult(result ScoreResult) {
	if jsonOutput || outputPath != "" {
		jsonResults = append(jsonResults, result)
	}

	if jsonOutput {
		return
	}

	fmt.Println(colorize("\n------[HEURISTIC SCORE]------", colorCyanBold))
	fmt.Printf("File         : %s\n", result.FilePath)
	if result.ErrorMessage != "" {
		fmt.Printf("Error        : %s\n", colorize(result.ErrorMessage, colorRed))
		return
	}

	fmt.Printf("Entropy      : %.4f bits/byte\n", result.Entropy)
	
	color := colorGreen
	if result.TrustScore < 50 {
		color = colorRed
	} else if result.TrustScore < 80 {
		color = colorYellow
	}

	fmt.Printf("Trust Score  : %s\n", colorize(fmt.Sprintf("%d/100", result.TrustScore), color+colorBold))
	fmt.Printf("Assessment   : %s\n", colorize(result.Assessment, color))
}

func init() {
	rootCmd.AddCommand(scoreCmd)
}
